import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>TODO motus == copier https://www.tusmo.xyz/</h1>
                <p>EN ANGLAIS CAR PAS API FR</p>
                <p>API https://random-word-api.herokuapp.com/word?number=1</p>
            </main>
        </div>
    );
}
